### ISSUE TITLE
email route process with chinese lang  problem

### ISSUE THREAD

**Issue by braveh4rt** [avleen/vexim2#12]
hi,

i got vexim-2.2.1_1 , with exim -postgresql-4.77 running.

My problem was when receive email with content have chinese language, in the router section which scan message got defer because the database said with error :
 
HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.
WARNING:  nonstandard use of escape in a string literal at character 108
HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.

this problem recorded in exim log : 

== #####@####.com R=ditch_hdrfrom defer (-1): condition check lookup defer

When i check the mail header with exim -Mvh , the from content chinese character.

The postgresql database already set using UTF8 encoding.

When i disable the ditch_hdrfrom in router, the message delivered. 

How to fix this encoding problem i guess...or how to fix this issue.

Thanks

**Comment by rimas-kudelis** [comment]
@braveh4rt: do you still want to have this resolved upstream? If you do, please paste an example header that fails without your patch and does not fail with it. Otherwise I will close this issue next sunday.

**Comment by rimas-kudelis** [comment]
Closing this because the OP hasn't responded for almost a year now.

**Comment by runout-at** [comment]
I reopen this because it seems i'd run into the same issue.
maybe this is also releated to #242 which i reported some weeks ago.

From: =?koi8-r?B?78zRIPPVyMHOz9fB?= <stix_alp@rambler.ru>

this might be russian charactars. i don't speak the language but i'm in kyrgyzstan at the moment.
Sorry, i've very little chance to do more analyses at the moment.

**Comment by rimas-kudelis** [comment]
Yes, this and #242 are possibly duplicates, except this one explicitly mentions PostgreSQL, and #242 mentions a MySQL variant.

We need more info to reach a conclusion though. Debug steps are provided in #242, though you have to adapt them for each header (from, to, mailer, subject). Also, information about the version of Vexim used would be helpful.
