### ISSUE TITLE
Dash in e-mailaddress/user-based aliases

### ISSUE THREAD

**Issue by Udera** [avleen/vexim2#28]
I found several discussions about dashes in e-mail-addresses (e.g. http://comments.gmane.org/gmane.mail.exim.vexim.devel/1973). In the standard-configuration 
````
local_part_suffix = -*
local_part_suffix_optional
````
is active. A nice thing for such a suffix is that you can easily use different addresses for specific purposes (e.g. user-github@example.org). But it is easy to guess your real address and the address for other purposes (user-amazon@example.org).

In the past, I used random addresses for different services (e.g. github-jdIU9@example.org). I created a forwarding address myself. Advantage of this method: if someone obtains my github-address, he won't be able to guess neither my amazon/banking/whatever-address nor my real address and I can easily disable it to prevent spam mails. Unfortunately, this technique only works for admin-users.

For me there are two questions:

1) Is this local-suffix used a lot? If most users are restrained by it, it might be better to disable it by default
2) If there is a bigger interest in some purpose-based alias which can be set up by each user. This could be a nice feature for vexim. Maybe even some temporary addresses?

**Comment by rimas-kudelis** [comment]
1) I can't answer about that. It might make sense asking in vexim or exim4u mailing lists, but you may or may not get your replies.
Furthermore, the feature you are talking about, even if it is used, it's likely that these users are so-called power users. I think these automated suffixes are only popular among geeks, meanwhile normal people just create a new mailbox, or use client-side e-mail filters to organize their messages.

2) Regarding purpose-based aliases: you are correct, it's easy to guess aliases such as -amazon and -github. But you can always use random aliases, such as -0x598911 for amazon and -12a62f for github. This way it will be easy to guess your real e-mail address, but not your aliases elsewhere.
By the way, I don't think these aliases are designed to be a security measure – they are available as a convenience feature, that's all.
It might be useful however, to have some sort of a "long-time random address" feature. For example, the administrator could configure a dedicated prefix for such use, and then the users could ask for a random alias, which Vexim would create for them. If implemented however, this should be easy to enable/disable a) completely, b) on a per-domain basis and c) on a per-user basis. Also, ideally, the users should be able to do that without logging in directly into Vexim management interface.

3) Temporary addresses is also a nice idea, but same constraints as above apply.

**Comment by Z3po** [comment]
Furthermore, the feature you are talking about, even if it is used, it's likely that these users are so-called power users. I think these automated suffixes are only popular among geeks, meanwhile normal people just create a new mailbox, or use client-side e-mail filters to organize their messages.
yes. It's definitely used by people. E.g. I'm using it myself (currently with having a catchall and configuring here and then some aliases) so i can use different mailaddresses for registration. That's pretty usefull in cases some company sells your mail adresses to recognize a) who did that and b) to black that email address completely.
I'd like to have that feature configurable on a user level. Downside here is that all adresses starting with the users localpart are then unusable and you shouldn't be able to create them in vexim.
Lon story short I think that shouldn't be disabled but at least shouldn't be enabled by default.

**Comment by Udera** [comment]
The ditch_* routers already removed this option in the conf.d/-files. I fixed this in the configure-file:
https://github.com/avleen/vexim2/pull/60

**Comment by Udera** [comment]
So we use the +-suffix by default, the pull request has been merged. Closing here.
