### ISSUE TITLE
Mail storage dir /var/spool/vexim ?

### ISSUE THREAD

**Issue by Kami-no** [avleen/vexim2#50]
Readme.md
* row 97 /var/spool/vexim/
* row 334 /usr/local/mail/

variables.php
* row 57 $mailroot = "/usr/local/mail/";

Confusing...

https://github.com/avleen/vexim2/pull/51

**Comment by Udera** [comment]
Oh, that is strange indeed. In debian, I have the mail of local users delivered to /var/mail/$localpart. /var/spool is only for temporary usage (e.g. exim queue).

We fixed some stuff over the last months, we need to review the documentation and make sure to have a working version.

**Comment by rimas-kudelis** [comment]
This is fixed by 7aa018aff625ca3400da30baf8f387dc70ebc42f.
