### ISSUE TITLE
Database-field complexpass

### ISSUE THREAD

**Issue by Udera** [avleen/vexim2#58]
I found the complexpass-field in the database but without any other reference in the code:
https://github.com/avleen/vexim2/blob/master/setup/mysql.sql#L22

Is this deprecated? Or is there any planned function?

**Comment by rimas-kudelis** [comment]
Huh, good question.
This field has been there since the very first commits in 2003 (see 76d497969bd8a517facc48064136e7412134a509), but I couldn't find any uses of it. Since we are certainly not using it now, I think it's safe to delete.
