### ISSUE TITLE
Sitechange broken

### ISSUE THREAD

**Issue by Udera** [avleen/vexim2#66]
* Go to the sitechangeadmin-page
* click on disable spamassassin for all domain users

All settings will be lost (maximum accounts, max quota, max message size, ...) or set to 0.Perhaps something went wrong at the last submission (or was broken already before): https://github.com/avleen/vexim2/commit/7114826b2bf15b0b71f6a87168c283b969b1b523

Running this query (https://github.com/avleen/vexim2/blob/master/vexim/sitechangesubmit.php#L59-L73) makes no sense if the user wants to disable spamassassin. The disable-spamassassin button activates a different form and all the variables won't be submitted.

I'm not sure if I understood this code correctly. Could you verify @Kami-no @rimas-kudelis ?

**Comment by Kami-no** [comment]
Looks like you're right, more conditions required or form should be modified%
* Verify if each variable is set before insert it's code into DB request (it gives flexibility for future but makes code more complex);
* Hidden field with variable for specific action (same situation with AV changed for all users) and trigger for that (simple option for exactly these cases).

It was made before my commit - https://github.com/avleen/vexim2/blame/master/vexim/sitechangesubmit.php#L59-L73

**Comment by Udera** [comment]
@Kami-no If you can have a look at it would be great

**Comment by Kami-no** [comment]
Here is the fix only: https://github.com/avleen/vexim2/pull/67

**Comment by rimas-kudelis** [comment]
> I'd recommend an upgrade to support both disable and enable. If it's ok, I'll make a bugfix for that.

Of course it's OK! :)

**Comment by Udera** [comment]
solved by: https://github.com/avleen/vexim2/pull/67

**Comment by rimas-kudelis** [comment]
Except the re-enabling part. ;)

**Comment by Udera** [comment]
Sorry, I didn't see this.

**Comment by Kami-no** [comment]
Well, it should be qualified as feature and not a bug =) I'll have time this week.

**Comment by rimas-kudelis** [comment]
> Well, it should be qualified as feature and not a bug =) 

Okay, it's been filed as #69 now. :)

> I'll have time this week.

Good to know!
