### ISSUE TITLE
A domain should not be created if its home dir cannot be created

### ISSUE THREAD

**Issue by rimas-kudelis** [avleen/vexim2#71]
If "Domain Mail directory" is filled incorrectly when creating a new domain (e.g. I had /var/vmail there, but this dir did not exist, and Apache didn't have permission to create it), Vexim will set new domain's homedir to `/domain.name/` (instead of `/var/vmail/domain.name/`). This is wrong and the domain should not be created at all in such situation. Instead, a proper error message should be presented to the user.

**Comment by Udera** [comment]
Normally the folder is created when exim delivers the first mail.

My webserver cannot (and should not) read the mail-folders. But we probably have to verify these realpath()-statements.

**Comment by rimas-kudelis** [comment]
Yes indeed, `realpath()` is the culprit. There's a replacement function for cases like ours published [here](http://stackoverflow.com/questions/20522605/what-is-the-best-way-to-resolve-a-relative-path-like-realpath-for-non-existing#20545583), perhaps we should use that?

**Comment by Udera** [comment]
Ok, I got it. I did a little test-script:
````
<?php
echo realpath('/var/www/test/');
echo "<br>";
echo realpath('/root/.ssh/');
echo "<br>";
echo realpath('/root/');
echo "<br>";
echo realpath('/var/vmail');
echo "<br>";
echo realpath('../../root/');
?>
````
output:
> /var/www/test
>
>/root
>/var/vmail
>/root

The webserver only needs to be able to read the parent (`/var`) of the maildir folder. Your linked script does give some strange results when you use relative paths.

Do you have your mail-storage within a protected folder?

**Comment by rimas-kudelis** [comment]
From http://php.net/realpath:
> `realpath()` returns `FALSE` on failure, e.g. if the file does not exist.

That is the problem.
I think I could check if the result of `realpath()` is FALSE, and fail with an error if it is. One problem I see with that is that it's still possible that the web server could have no access to actually know if the dir exists. Although that seems quite unlikely, considering that there haven't been bug reports about this until now.

**Comment by Udera** [comment]
Do you use `open_basedir`-restrictions? Normally, you should be able to read `/var`

Perhaps we should return an error if `realpath()` is empty?

**Comment by rimas-kudelis** [comment]
> Do you use `open_basedir`-restrictions? Normally, you should be able to read `/var`

No, I just didn't have `/var/vmail` at all in the VM I used for testing my migration scripts.

> Perhaps we should return an error if `realpath()` is empty?

Yeah, I suggest we do. Or we could clean up our path using a regex. I don't think that for example replacing all symlinks we encounter in our path with their real paths is desired. I'd rather just have all `/../`'s and `/./`'s cleaned up.

**Comment by Udera** [comment]
We mostly use absolute path in the configuration (https://github.com/avleen/vexim2/blob/master/vexim/config/variables.php.example#L60). We could apply `realpath()` only if there is a relative path and if `realpath()` fails, the user is told to use an absolute path.

If there is a typo in your absolute path, exim will show an error and then it will be harder to identify the problem.

**Comment by rimas-kudelis** [comment]
Is there a case for using relative paths there? It seems quite wrong to me.

**Comment by Udera** [comment]
No, we only used absolute paths (config-files, documentation). It's only about testing if the parent folder for the mailboxes has been created. In that point it did work for your case ("forgotten to create the folder"), except it didn't show a helpful error message.

**Comment by rimas-kudelis** [comment]
OK, here's what I did:
- added a boolean setting `$testmailroot` to `variables.php.example`, which defaults to `true`.
- if `$_POST['maildir']` does not start with a slash character, domain creation always fails.
- if the `$testmailroot` setting is true, I check whether `$_POST['maildir']` exists before creating a domain, and if it does not, domain creation fails.
- I only call `realpath()` once now, that's when and if I test that the actual directory exists and is a directory. I don't use the returned path and don't put it into the database though.
@Udera, would you look through the patch in #75 please? If it's fine, I'll merge it in.
